# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vigas.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(581, 579)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/logos/logofcsoft-icono.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 2)
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setAutoFillBackground(False)
        self.label_12.setStyleSheet(_fromUtf8(""))
        self.label_12.setText(_fromUtf8(""))
        self.label_12.setPixmap(QtGui.QPixmap(_fromUtf8(":/logos/logofcsoft-1-256x256.png")))
        self.label_12.setScaledContents(False)
        self.label_12.setOpenExternalLinks(False)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 0, 4, 2, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.AceroBox = QtGui.QComboBox(self.centralwidget)
        self.AceroBox.setObjectName(_fromUtf8("AceroBox"))
        self.AceroBox.addItem(_fromUtf8(""))
        self.AceroBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.AceroBox, 1, 1, 1, 1)
        self.HormBox = QtGui.QComboBox(self.centralwidget)
        self.HormBox.setObjectName(_fromUtf8("HormBox"))
        self.HormBox.addItem(_fromUtf8(""))
        self.HormBox.addItem(_fromUtf8(""))
        self.HormBox.addItem(_fromUtf8(""))
        self.HormBox.addItem(_fromUtf8(""))
        self.HormBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.HormBox, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.tipo = QtGui.QComboBox(self.centralwidget)
        self.tipo.setObjectName(_fromUtf8("tipo"))
        self.tipo.addItem(_fromUtf8(""))
        self.tipo.addItem(_fromUtf8(""))
        self.tipo.addItem(_fromUtf8(""))
        self.tipo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.tipo, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 3, 2, 1, 1)
        self.calcular = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.calcular.setFont(font)
        self.calcular.setObjectName(_fromUtf8("calcular"))
        self.gridLayout_3.addWidget(self.calcular, 3, 4, 1, 1)
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_9 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.L = QtGui.QLineEdit(self.widget)
        self.L.setMinimumSize(QtCore.QSize(0, 20))
        self.L.setMaximumSize(QtCore.QSize(50, 16777215))
        self.L.setObjectName(_fromUtf8("L"))
        self.gridLayout_2.addWidget(self.L, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.H = QtGui.QLineEdit(self.widget)
        self.H.setMinimumSize(QtCore.QSize(0, 20))
        self.H.setMaximumSize(QtCore.QSize(50, 16777215))
        self.H.setObjectName(_fromUtf8("H"))
        self.gridLayout_2.addWidget(self.H, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.B = QtGui.QLineEdit(self.widget)
        self.B.setMinimumSize(QtCore.QSize(0, 20))
        self.B.setMaximumSize(QtCore.QSize(50, 16777215))
        self.B.setObjectName(_fromUtf8("B"))
        self.gridLayout_2.addWidget(self.B, 2, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 3, 0, 1, 1)
        self.rec = QtGui.QLineEdit(self.widget)
        self.rec.setMinimumSize(QtCore.QSize(0, 20))
        self.rec.setMaximumSize(QtCore.QSize(50, 16777215))
        self.rec.setObjectName(_fromUtf8("rec"))
        self.gridLayout_2.addWidget(self.rec, 3, 1, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 4, 0, 1, 2)
        self.TablaCargas = QtGui.QTableWidget(self.centralwidget)
        self.TablaCargas.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.TablaCargas.setFont(font)
        self.TablaCargas.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TablaCargas.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TablaCargas.setAutoScroll(True)
        self.TablaCargas.setObjectName(_fromUtf8("TablaCargas"))
        self.TablaCargas.setColumnCount(1)
        self.TablaCargas.setRowCount(4)
        item = QtGui.QTableWidgetItem()
        self.TablaCargas.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.TablaCargas.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.TablaCargas.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.TablaCargas.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.TablaCargas.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.TablaCargas.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.TablaCargas.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.TablaCargas.setItem(3, 0, item)
        self.gridLayout_3.addWidget(self.TablaCargas, 4, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 4, 4, 1, 1)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 5, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 5, 2, 1, 1)
        self.resultados = QtGui.QTableWidget(self.centralwidget)
        self.resultados.setObjectName(_fromUtf8("resultados"))
        self.resultados.setColumnCount(3)
        self.resultados.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.resultados.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.resultados.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.resultados.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.resultados.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.resultados.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.resultados.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.resultados.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.resultados.setHorizontalHeaderItem(2, item)
        self.resultados.horizontalHeader().setDefaultSectionSize(150)
        self.gridLayout_3.addWidget(self.resultados, 6, 0, 1, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.HormBox, self.AceroBox)
        MainWindow.setTabOrder(self.AceroBox, self.tipo)
        MainWindow.setTabOrder(self.tipo, self.TablaCargas)
        MainWindow.setTabOrder(self.TablaCargas, self.resultados)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Programa para Calculo de Vigas - Felipe Cordero O.", None))
        self.label_4.setText(_translate("MainWindow", "Parámetros Básicos de Diseño", None))
        self.label.setText(_translate("MainWindow", "Hormigón", None))
        self.AceroBox.setItemText(0, _translate("MainWindow", "A6342H", None))
        self.AceroBox.setItemText(1, _translate("MainWindow", "A4428H", None))
        self.HormBox.setItemText(0, _translate("MainWindow", "H20", None))
        self.HormBox.setItemText(1, _translate("MainWindow", "H25", None))
        self.HormBox.setItemText(2, _translate("MainWindow", "H30", None))
        self.HormBox.setItemText(3, _translate("MainWindow", "H35", None))
        self.HormBox.setItemText(4, _translate("MainWindow", "H40", None))
        self.label_3.setText(_translate("MainWindow", "Tipo de viga", None))
        self.tipo.setItemText(0, _translate("MainWindow", "Apoyado-Apoyado", None))
        self.tipo.setItemText(1, _translate("MainWindow", "Apoyado-Empotrado", None))
        self.tipo.setItemText(2, _translate("MainWindow", "Empotrado-Empotrado", None))
        self.tipo.setItemText(3, _translate("MainWindow", "Voladizo (x 1.3 incluido)", None))
        self.label_2.setText(_translate("MainWindow", "Acero", None))
        self.label_5.setText(_translate("MainWindow", "Dimensiones:", None))
        self.label_11.setText(_translate("MainWindow", "Definición de Cargas:", None))
        self.calcular.setText(_translate("MainWindow", "Calcular!", None))
        self.label_9.setText(_translate("MainWindow", "Largo [m] =", None))
        self.label_6.setText(_translate("MainWindow", "H [cm]=", None))
        self.label_7.setText(_translate("MainWindow", "B [cm]=", None))
        self.label_10.setText(_translate("MainWindow", "rec [cm]=", None))
        item = self.TablaCargas.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ancho Tributario [m]", None))
        item = self.TablaCargas.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Espesor Losa [cm]", None))
        item = self.TablaCargas.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "CM [kg/m2]", None))
        item = self.TablaCargas.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "SC [kg/m2]", None))
        item = self.TablaCargas.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Cargas", None))
        __sortingEnabled = self.TablaCargas.isSortingEnabled()
        self.TablaCargas.setSortingEnabled(False)
        self.TablaCargas.setSortingEnabled(__sortingEnabled)
        self.label_8.setText(_translate("MainWindow", "Resultados:", None))
        item = self.resultados.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Momento [ton-m]", None))
        item = self.resultados.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", " ρ / ρb [%]", None))
        item = self.resultados.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Corte [ton]", None))
        item = self.resultados.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Def. LP [cm]", None))
        item = self.resultados.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Def Inst. [cm]", None))
        item = self.resultados.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Izquierda", None))
        item = self.resultados.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Centro", None))
        item = self.resultados.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Derecha", None))

import images_rc
